name: Cloud integration
on:
  push:
    paths-ignore:
    - '*.md'
    - '**/*.md'
    branches:
    - main
env:
  GH_ANNOTATION: true
  DOCKER_BUILDKIT: 1
jobs:
  docker_build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        target: [cli-bin]
    name: Docker build (${{ matrix.target }})
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Set environment variables from scripts
      run: |
        . bin/_tag.sh
        echo ::set-env name=TAG::$(CI_FORCE_CLEAN=1 bin/root-tag)

        . bin/_docker.sh
        echo ::set-env name=DOCKER_REGISTRY::$DOCKER_REGISTRY
        echo ::set-env name=DOCKER_BUILDKIT_CACHE::${{ runner.temp }}/.buildx-cache
    - name: Cache docker layers
      # actions/cache@v2.0.0
      uses: actions/cache@b820478
      with:
        path: ${{ env.DOCKER_BUILDKIT_CACHE }}
        key: ${{ runner.os }}-buildx-${{ matrix.target }}-${{ env.TAG }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ matrix.target }}-
    - name: Build docker images
      env:
        DOCKER_TRACE: 1
      run: |
        docker buildx create --driver docker-container --use
        bin/docker-build-${{ matrix.target }}
    - name: Push docker images to registry
      run: |
        . bin/_docker.sh
        docker_push "${{ matrix.target }}" "$TAG"
        docker_retag "${{ matrix.target }}" "$TAG" main
        docker_push "${{ matrix.target }}" main
    - name: Prune docker layers cache
      # changes generate new images while the existing ones don't get removed
      # so we manually do that to avoid bloating the cache
      run: bin/docker-cache-prune
  # todo: Keep in sync with `release.yml`
